Added Atan2Op support
tenstorrent/tt-mlir pull request #1056
Opened 2024-10-24 15:34 UTC by kmitrovicTT

Added Atan2Op to TTIR and TTNN ops. Added stablehlo to ttir conversion. Added ttir to ttnn conversion. Added tests.

2024-10-24 16:25 UTC, AleksKnezevic approved these changes

2024-10-25 13:04 UTC, kmitrovicTT commented
Seems like `ttnn::atan2` reverses arguments compared to stablehlo/numpy/torch. Will check with ttnn crew why this is the case, and whether it should be fixed on their end, or if I should reverse args in stablehlo -> ttir pass.

2024-10-28 16:55 UTC, svuckovicTT commented on third_party/CMakeLists.txt
> +set(TT_METAL_VERSION "fccd6929c7a065b9145af92b1a429b2e8f63907b")
Not sure if this was intentional, or just got picked up during git add. Leaving comment as a reminder to remove before merging.

2025-02-21 01:34 UTC, nsmithtt commented
This is an old PR, perhaps we can close?

2025-02-24 09:20 UTC, kmitrovicTT commented
Metal issue is still open https://github.com/tenstorrent/tt-metal/issues/14470

2025-02-24 10:19 UTC, sdjordjevicTT commented
> Metal issue is still open [tenstorrent/tt-metal#14470](https://github.com/tenstorrent/tt-metal/issues/14470). It is a P2 issue, I assume that's why no one is fixing it.

I pinged Chris to find the actual owner. Let's get at least an input from them about the issue. :)

2025-02-27 12:39 UTC, kmitrovicTT commented
Metal issue is fixed. I'll continue this effort once I have some spare time, I am currently working on higher priority issues.

2025-03-31 14:05 UTC, svuckovicTT requested changes
Please add an emitc test as well.

2025-03-31 14:18 UTC, azecevicTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +        // %result: [0.0, 1.57079637, -1.57079637] // [0.0, pi/2, -pi/2]
Is `atan2(0, 0) = 0` what TTNN returns? Either way it's not the best idea to take undefined value as an example especially in TTIR, unless we want to commit to this behavior long-term.

2025-03-31 14:18 UTC, azecevicTT commented on test/ttmlir/Conversion/StableHLOToTTIR/binary/atan2_op.mlir
> +    // CHECK: %[[C:.*]] = ttir.empty[[C:.*]]
Please don't use `%[[C:.*]]...[[C:.*]]` anymore.

2025-03-31 14:40 UTC, mmanzoorTT approved these changes

2025-03-31 16:43 UTC, svuckovicTT approved these changes

2025-03-31 16:44 UTC, azecevicTT approved these changes
Looks good now, one more comment regarding the example.

2025-03-31 16:44 UTC, azecevicTT commented on include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
> +        // %rhs: [0.0, 0.0, 0.0]
Let's change the example here as well. Btw, `(0, 1) = 0` might be the more canonical example.

2025-04-01 08:31 UTC, sdjordjevicTT approved these changes

2025-04-01 08:33 UTC, sdjordjevicTT commented on lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
> +           EltwiseBinaryOpConversionPattern<tt::ttnn::Atan2Op>>(typeConverter,
Looking at the C++ implementation in metal, Atan2 op is a binary composite, so you should use EltwiseBinaryCompositeOpConversionPattern here.

2025-04-01 08:40 UTC, kmitrovicTT commented on lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
> +           EltwiseBinaryOpConversionPattern<tt::ttnn::Atan2Op>>(typeConverter,
Tnx!

2025-04-01 11:27 UTC, merged