Add graph capture validation pass
tenstorrent/tt-mlir pull request #1195
Opened 2024-11-07 16:38 UTC by derdeljanTT

Implement a mlir pass which performs graph capture validation of output TTNN graph. By default, this pass is disabled. https://github.com/tenstorrent/tt-mlir/issues/1183

fyi @mbezuljTT @s-jovic

2024-11-07 17:06 UTC, tapspatel commented on runtime/tools/python/ttrt/common/run.py
> +                                    self["--use-graph-capture"],
can we add this in trt.runtime.DebugEnv? It seems like this feature is a debug mode feature and the infra is already there to add specific bools like this one

debug_env = ttrt.runtime.DebugEnv.get(
                self["--load-kernels-from-disk"], self["--enable-async-ttnn"]
            )

2024-11-07 17:06 UTC, tapspatel commented on runtime/lib/ttnn/program.cpp
> +  if (useGraphCapture) {
this would be something like debug::Env::get().useGraphCapture

2024-11-07 17:07 UTC, tapspatel requested changes
changes inlined

2024-11-18 15:41 UTC, nobradovictt commented on include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
> +  Option<bool> graphCaptureValidationEnabled{
You lack a test using this option.

2024-11-18 15:41 UTC, nobradovictt commented on lib/Dialect/TTNN/Transforms/Passes.cpp
> +    std::error_code _ec;
What happens in case of failure?

2024-11-18 15:41 UTC, nobradovictt commented on lib/Dialect/TTNN/Transforms/Passes.cpp
> +    outputFlatBufferFile(mlirFilePath, flatBufferFilePath);
How are failures in each stage handled, how do you know you are not reading artefact of some previous compile session?

2024-11-18 15:41 UTC, nobradovictt commented on lib/Dialect/TTNN/Transforms/Passes.cpp
> +    const std::string cmd = "ttrt run " + flatBufferFilePath +
Do we have something like std::format to allow plugin of parameters within const string?

2024-11-18 15:41 UTC, nobradovictt commented on lib/Dialect/TTNN/Transforms/Passes.cpp
> +    if (!isValidGraphCaptureReport(outReportPath)) {
IsValid needs to return more than bool. It needs to be loc<->op type mapping to ->  exception type.

2024-11-18 15:41 UTC, nobradovictt commented on lib/Dialect/TTNN/Transforms/Passes.cpp
> +    if (!isValidGraphCaptureReport(outReportPath)) {
Then handlers need to be written for every exception type.

2024-11-18 15:41 UTC, nobradovictt commented on runtime/lib/ttnn/program.cpp
> +        } catch (const std::exception &ex) {
Can this leave device in a bad state? Can it leak memory?

2024-11-20 21:18 UTC, mbezuljTT commented
Thanks everyone for great feedback on the implementation! I'll close PR per explanation I've wrote on the issue #1183
I think we have a good plan to move forward, but it will take us some time to get there.

2024-11-20 21:18 UTC, closed without merging