Add EmbeddingBackward op e2e
tenstorrent/tt-mlir pull request #1419
Opened 2024-11-26 13:04 UTC by rpavlovicTT

TTNN implements EmbeddingBackward op that computes gradient of the embedding weights w.r.t. input tokens, and gradient of the previous op in backward graph.
This commit adds support for using this op through tt-mlir.

2024-12-05 13:06 UTC, svuckovicTT requested changes

2024-12-05 13:06 UTC, svuckovicTT commented on runtime/lib/ttnn/program.cpp
> +#include "operations/embedding/embedding_backward.h"
Would you mind adding this include (and the `embedding.h` one) to the `tools/ttnn-standalone/ttnn-precompiled.hpp`?

2024-12-05 13:06 UTC, svuckovicTT commented on include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
> +                         AnyRankedTensor:$output);
This doesn't fully reflect the signature of `ttnn::embedding_bw`'s invoke. Add
```
        const std::optional<const DataType> dtype = std::nullopt,
        const std::optional<MemoryConfig>& memory_config = std::nullopt,
```

2024-12-05 13:06 UTC, svuckovicTT commented on runtime/lib/ttnn/operations/embedding/embedding_backward.cpp
> +      utils::createMemoryConfig(op->in_grad());
This should be read from params once they're added in `include/ttmlir/Dialect/TTNN/IR/TTNNOps.td`.

2024-12-05 14:37 UTC, rpavlovicTT commented on lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
> +static ttnn::ReshapeOp generateReshape(Value input, ArrayRef<int64_t> newShape,
I am not sure if that's right way. Right now they are static to this file, as they are not used in any other place. If we put them in utils they will be globally visible. Do you still prefer having them in utils?

btw these 2 functions were just moved within the same file, I did not add them.

2024-12-06 10:27 UTC, svuckovicTT commented on lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
> +static ttnn::ReshapeOp generateReshape(Value input, ArrayRef<int64_t> newShape,
We can create a utils file for the conversion itself, and put all of these there. [Example](https://github.com/tenstorrent/tt-mlir/pull/1476/files#diff-05f866336c89bd537c3ee19244e211733dcbab69d6654e045ba205568eaccca7). (Note the namespace)

2024-12-09 10:16 UTC, svuckovicTT approved these changes

2024-12-11 15:59 UTC, kmabeeTT approved these changes
Thanks Radenko - rt changes lgtm.

2024-12-11 22:15 UTC, nsmithtt approved these changes

2024-12-12 07:04 UTC, merged