Added UpsampleOp support
tenstorrent/tt-mlir pull request #1422
Opened 2024-11-26 17:19 UTC by azecevicTT

E2E support of UpsampleOp. Few notes:
- channel_first = true currently fails during decomposition. The idea is to decompose `ttir.upsample(...)<{channel_first = true}>` into next snippet, after https://github.com/tenstorrent/tt-mlir/issues/652 is ready. I've marked all places in the code that are affected by this.
```
ttir.permute(...)<{permutation = [0, 2, 3, 1]}>
ttir.upsample(...)
ttir.permute(...)<{permutation = [0, 3, 1, 2]}>
```

- ttnn interface for upsample is weird to say the least, hopefully it's going to be fixed in the future. That's the reason why I decided to impose restrictions of scale_factor in TTNN dialect. I've also marked all affected places in the code, and I will track the changes on the metal side https://github.com/tenstorrent/tt-mlir/issues/1385.

Closes https://github.com/tenstorrent/tt-mlir/issues/1229

2024-12-09 01:59 UTC, nsmithtt commented
Do you think we should call this op Upsample2dOp?

@LPanosTT can you review?

2024-12-09 02:14 UTC, LPanosTT requested changes
Looks good to me! If you could also edit the PoolingOp and ConvolutionOp decomposition patterns to also use permute when converting to channel last rather than transpose that would be great too. It will be better to just use one op for permutations to make future TM removal passes cleaner to implement.

@nsmithtt I agree it should be named Upsample2D

2024-12-09 02:14 UTC, LPanosTT commented on lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
> +class UpsampleToUpsampleConversionPattern
I would call this something like `CannonicalizeChannelLastUpsample`. Just so you get a quick understanding of what it’s doing.

2024-12-09 09:22 UTC, azecevicTT commented
@LPanosTT Yeah, I planned to do that, though this PR is blocked (I rebased this branch on top of it mainly to test decomposition of upsample) by https://github.com/tenstorrent/tt-mlir/pull/1505, which is blocked by https://github.com/tenstorrent/tt-metal/issues/15750 :) The issue on metal has high probability of breaking the runtime of permute op, that's why I set both of these PRs to a draft state. Once that issue is resolved I plan to replace all transpose decompositions with permute and land them as a part of https://github.com/tenstorrent/tt-mlir/pull/1505, which makes more sense, as these have little to do with UpsampleOp.

@nsmithtt I thought about that name for TTIR as well as it describes this op more precisely, and leaves room for some other variants of upsample in the future. I would still prefer calling it "upsample" in the TTNN dialect, to maintain 1-1 correspondence with the lib. What do you think about that?

2024-12-09 17:03 UTC, nsmithtt commented
> @nsmithtt I thought about that name for TTIR as well as it describes this op more precisely, and leaves room for some other variants of upsample in the future. I would still prefer calling it "upsample" in the TTNN dialect, to maintain 1-1 correspondence with the lib. What do you think about that?

We have a similar pattern on the convolution/pooling side of things, i.e.:
- `ConvolutionOp`: Captures all kinds of convolutions generically, 1d/2d/3d/etc any ranked tensors, transposed, etc.
- `Conv2dOp`: A particular specialization of `ConvolutionOp` that is much easier to work with and lower, but only captures 2d convs.

Upsample is in the same family as convolution and pooling ops which have already established this convention in the TTIR dialect.  The way you have defined this op currently is in the form of the second bullet so I would recommend naming it `Upsample2dOp` for this reason.  Or we have to redefine the op to be much more generic than how it reads now which might be too much of an undertaking to do at the moment.

2025-01-16 13:45 UTC, jserbedzijaTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +        %0 = "ttir.upsample"(%a, %output) <{scale_factor = array<i32: 2, 4>}> : (tensor<10x64x32x3xbf16>, tensor<10x128x128x3xbf16>) -> tensor<10x64x128x3xbf16>
You should write "ttir.upsample2d" instead of "ttir.upsample"

2025-01-16 13:46 UTC, jserbedzijaTT commented on include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
> +def TTNN_UpsampleOp : TTNN_Op<"upsample"> {
Should we also rename this to `upsample2d`?

2025-01-16 13:50 UTC, jserbedzijaTT commented on lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
> +            /*channel_last=*/true);
Can we somehow abstract this logic so it can be used for any op that wants to support both channel first and channel last?

2025-01-16 14:00 UTC, jserbedzijaTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +      - `scale_factor` (si32 | array<i32>): The scale factor for upsampling in H and W dimensions respectively.
Why do you use `si32` here when `scale_factor` is a single integer? Is it because arrays implicitly use signed integers to store values and you want to keep the types consistent?

2025-01-29 16:12 UTC, LPanosTT approved these changes

2025-01-29 17:31 UTC, sdjordjevicTT approved these changes
Thanks for the detailed tests!

Just left a comment about whether we want to include the channel_last attribute as part of the TTIR op definition...

2025-01-29 17:31 UTC, sdjordjevicTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +                         DefaultValuedAttr<BoolAttr, "true">:$channel_last);
I am not sure if we should follow this comment from @nsmithtt here:
https://github.com/tenstorrent/tt-mlir/pull/1664/files#r1905796821

My take here would be that on the TTIR level, we should allow the channel_last attribute, but once we lower to TTNN, we should convert default what TTNN supports, or even do it in decomposition...

2025-01-29 17:31 UTC, sdjordjevicTT commented on lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
> +            /*channel_last=*/true);
Let's create an issue so we don't forget about this. :)

2025-01-29 17:46 UTC, azecevicTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +                         DefaultValuedAttr<BoolAttr, "true">:$channel_last);
I believe this is the most pragmatic approach for now and would cover the most frontends, if there appears a need for more general UpsampleOp we can rethink this approach.

2025-01-29 17:56 UTC, nsmithtt commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +                         DefaultValuedAttr<BoolAttr, "true">:$channel_last);
The issue with this attribute is that `channel_last=False` is unlowerable to TTNN so we're forced to deal with it somewhere in the lowering pipeline.  It's better to deal with it during TTIR and imo it's better to stick with the established convention, i.e. the low level `2d` ops are only channels last ops, full stop.

2025-01-29 18:21 UTC, azecevicTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +                         DefaultValuedAttr<BoolAttr, "true">:$channel_last);
Consistency-wise I agree, I have removed it, I'm just not sure about the path from here, we will have to think wisely how that general UpsampleOp should look like, because I doubt we will see the support for something other than Upsample2d in TTNN any time soon.

2025-01-29 21:33 UTC, jnie-TT commented on runtime/lib/ttnn/operations/pool/upsample.cpp
> +    DEBUG_ASSERT(false);
This should probably be a fatal error instead of only a debug check

2025-01-29 21:33 UTC, jnie-TT commented on runtime/lib/ttnn/operations/pool/upsample.cpp
> +  ::ttnn::Tensor output = ::ttnn::upsample(input, scaleFactor, mode);
Forgot to pass the memory config in

2025-01-29 21:33 UTC, jnie-TT commented on runtime/lib/ttnn/operations/pool/upsample.cpp
> +  tensorPool.insert_or_assign(op->out()->global_id(), std::move(output));
Let's not move ttnn tensors unless necessary, we're not saving much in performance anyway

2025-01-29 21:33 UTC, jnie-TT commented on runtime/lib/ttnn/operations/CMakeLists.txt
> +  ${CMAKE_CURRENT_SOURCE_DIR}/pool/upsample.cpp
Nit: Move this up so that it groups together with pool/maxpool2d.cpp

2025-01-29 21:43 UTC, azecevicTT commented on runtime/lib/ttnn/operations/pool/upsample.cpp
> +  ::ttnn::Tensor output = ::ttnn::upsample(input, scaleFactor, mode);
Yeah, good catch, thanks!

2025-01-29 21:45 UTC, azecevicTT commented on runtime/lib/ttnn/operations/pool/upsample.cpp
> +  tensorPool.insert_or_assign(op->out()->global_id(), std::move(output));
Tbh don't know how I even ended up with `std::move` here, especially because `insert_or_assign` takes `const &`, so `std::move` doesn't even make sense here.

2025-01-29 21:55 UTC, tapspatel approved these changes

2025-01-29 22:13 UTC, jnie-TT approved these changes

2025-01-30 03:19 UTC, nsmithtt approved these changes
Looks good, thank you!

2025-01-30 11:31 UTC, merged