initial check-in
tenstorrent/tt-mlir pull request #1602
Opened 2024-12-15 07:43 UTC by TT-billteng

2024-12-28 08:16 UTC, TT-billteng commented on lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
> +  op->walk([&](func::FuncOp entry) {
Is there a better way to extract the nested `FuncOp` from `ModuleOp`?

2024-12-28 08:18 UTC, TT-billteng commented on lib/Target/TTKernel/TTKernelToCppRegistration.cpp
> +      "tensixkernel-to-cpp", "translate tensix kernel to C++",
Feel like I need to change the option to `ttkernel-to-cpp=noc` and `ttkernel-to-cpp=tensix`

2024-12-28 08:18 UTC, TT-billteng commented on lib/Target/TTKernel/TTKernelToCppRegistration.cpp
> +      "tensixkernel-to-cpp", "translate tensix kernel to C++",
Is this possible? If so, where can I find an example?

2025-01-09 22:58 UTC, nsmithtt approved these changes
Hey Bill, sorry I was on vacation, still catching up on reviews.  This looks great a couple of minor nits and comments inline, but all optional.

2025-01-09 22:58 UTC, nsmithtt commented on include/ttmlir/Target/TTKernel/TTKernelToCpp.h
> +enum class ThreadType : uint32_t;
Nit: Should we include `"ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.h"` instead of doing a forward declare?  Would also prevent having an enum passed by reference.

2025-01-09 22:58 UTC, nsmithtt commented on lib/Target/TTKernel/TTKernelToCppRegistration.cpp
> +      "tensixkernel-to-cpp", "translate tensix kernel to C++",
I only know how to do this using the `-opt` tool, the translate MLIR tool seems much less featureful in terms of CLI.  Maybe we could do `--ttkernel-to-cpp-tensix` and `--ttkernel-to-cpp-noc`?  It's probably OK the way you have it too.

2025-01-09 22:58 UTC, nsmithtt commented on lib/Target/TTKernel/TTKernelToCppRegistration.cpp
> +// TODO: Should generalize this to read kernel type from Attribute?
This is true too, we could attach an attribute to the func op via [`op->setDiscardableAttr`](https://mlir.llvm.org/doxygen/classmlir_1_1Operation.html#a55a7c816fbfdb0840b59c722b6020833).

I think the IR would like:
```mlir
func.func @ttkernel_noc() -> () attributes { ttkernel.thread_type = #ttkernel.thread_type<tensix> } {
```

2025-01-10 10:06 UTC, sdjordjevicTT requested changes
Just a few minor comments that I would like your follow up.

2025-01-10 10:06 UTC, sdjordjevicTT commented on lib/Target/TTKernel/TTKernelToCppRegistration.cpp
> +      "tensixkernel-to-cpp", "translate tensix kernel to C++",
I am more for what @nsmithtt suggested, it aligns better with the rest of the codebase:
--ttkernel-to-cpp-tensix
--ttkernel-to-cpp-noc

2025-01-10 10:06 UTC, sdjordjevicTT commented on test/ttmlir/Translate/TTKernel/ttkernel_noc.mlir
> +// RUN: ttmlir-translate --nockernel-to-cpp %s
Should we have some checks in this file check to verify the test as we have in test/ttmlir/Translate/TTKernel/ttkernel_tensix.mlir test?

2025-01-10 22:24 UTC, TT-billteng commented on test/ttmlir/Translate/TTKernel/ttkernel_noc.mlir
> +// RUN: ttmlir-translate --nockernel-to-cpp %s
what are best practices around checking the validity of emitted C++?

2025-01-14 03:14 UTC, TT-billteng commented on lib/Target/TTKernel/TTKernelToCppRegistration.cpp
> +      "tensixkernel-to-cpp", "translate tensix kernel to C++",
done

2025-01-14 03:16 UTC, TT-billteng commented on lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
> +  std::vector<func::FuncOp> ops;
done

2025-01-14 03:16 UTC, TT-billteng commented on test/ttmlir/Translate/TTKernel/ttkernel_noc.mlir
> +// RUN: ttmlir-translate --nockernel-to-cpp %s
added CHECK statements

2025-01-14 03:18 UTC, TT-billteng commented on include/ttmlir/Target/TTKernel/TTKernelToCpp.h
> +enum class ThreadType : uint32_t;
OK let's do it since compile times aren't a concern here most likely

2025-01-14 15:45 UTC, sdjordjevicTT commented on test/ttmlir/Translate/TTKernel/ttkernel_noc.mlir
> +// RUN: ttmlir-translate --nockernel-to-cpp %s
Great! Thanks!

2025-01-14 15:45 UTC, sdjordjevicTT approved these changes

2025-01-15 16:03 UTC, svuckovicTT approved these changes

2025-01-15 16:03 UTC, svuckovicTT commented on include/ttmlir/Target/TTKernel/TTKernelToCpp.h
> +
nit: remove empty line

2025-01-16 00:05 UTC, TT-billteng commented on lib/Target/TTKernel/TTKernelToCpp.cpp
> +#include <llvm/Support/raw_ostream.h>
does clang-tidy help with this?

2025-01-16 22:36 UTC, TT-billteng commented on lib/Target/TTKernel/TTKernelToCppRegistration.cpp
> +#include <mlir/Dialect/MemRef/IR/MemRef.h>
ok done

2025-01-16 22:38 UTC, TT-billteng commented on include/ttmlir/Target/TTKernel/TTKernelToCpp.h
> +
done

2025-01-16 22:40 UTC, TT-billteng commented on lib/Target/TTKernel/TTKernelToCpp.cpp
> +#include <llvm/Support/raw_ostream.h>
fix

2025-01-17 00:19 UTC, merged