End-to-End Conversion for Round Op
tenstorrent/tt-mlir pull request #1651
Opened 2024-12-20 18:10 UTC by ddilbazTT

Stablehlo has 2 different round ops:
- round nearest even
- round nearest away from zero (or simply, round)

These two are lowered into ttir::roundNearestEvenOp and ttir::roundOp. Then, both are lowered into ttnn::roundOp.

ttnn::roundOp is a unary composite op with integer parameter determining which rounding mechanism to use. The parameters are introduced in ttir op level and passed unchanged to ttnn.

2024-12-25 15:56 UTC, azecevicTT commented on include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
> +        Variadic<AnyRankedTensor>:$inputs,
Why `Variadic` when `ttnn.round` takes just one tensor? Also it takes `std::optional<MemoryConfig>`.

2024-12-25 15:57 UTC, azecevicTT commented on include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
> +    let results = (outs Variadic<AnyRankedTensor>:$result);
Same as above, why `Variadic` result?

2024-12-25 16:42 UTC, azecevicTT requested changes
Can you write an explanation of the `decimals` parameter and check it once again in TTNN if it really works the way you thought?

2024-12-25 16:42 UTC, azecevicTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +def TTIR_RoundOp : TTIR_DPSOp<"round"> {
What's the rationale behind adding these two as separate ops in TTIR dialect? They have a similar behaviour that can be captured with one bool or enum that can later be interpreted during lowering.

2024-12-25 16:42 UTC, azecevicTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +        DefaultValuedAttr<I32Attr, "0">:$decimals
What's the meaning of the `decimals` attribute? I would assume it's the number of significant digits after decimal point we are rounding to, but that doesn't look like the case here, so some explanation would be welcome. Same for the `TTIR_RoundOp`. It's also very questionable if we really need both of these ops, we are mostly dealing with low precision floating point types, I doubt the type of rounding will cause any significant change here.

2024-12-25 16:42 UTC, azecevicTT commented on lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
> +               DefaultOpConversionPattern<ttnn::RoundOp>,
You've added it twice.

2024-12-25 16:42 UTC, azecevicTT commented on lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
> +    if (isa<stablehlo::RoundOp>(srcOp)) {
This seems like a waste, using template parameters that will be dynamically queried anyway.

2024-12-25 16:42 UTC, azecevicTT commented on lib/Dialect/TTIR/IR/TTIROps.cpp
> +  if (getDecimals() == 0) {
Even if this was true (which I doubt), this is a really bad design. If a type can have just one value then it's isomorphic to void and shouldn't be a parameter at all, it should be explicitly set during lowering if appropriate op on lower level dialect requires it.

2024-12-25 16:42 UTC, azecevicTT commented on test/ttmlir/Conversion/StableHLOToTTIR/round_op.mlir
> +    // CHECK: %[[C:.*]] = tensor.empty[[C:.*]]
`[[C:.*]] =` means store everything up to `=` into variable `C`, but we never use `C` so the simplest way to check if op appears in output of `ttmlir-opt` is just `// CHECK: tensor.empty`. Same for the other checks.

2025-01-06 09:49 UTC, ddilbazTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +def TTIR_RoundOp : TTIR_DPSOp<"round"> {
I mapped stablehlo ops 1-to-1 in TTIR as that's what was decided on (stablehlo ops mapping to ttir ops). There are two round ops in stablehlo but there is only one ttnn round op that can cover them both. So ttir has two round ops mapping directly to their stablehlo counterparts but the decimals arguments in ttir ops helps mapping to ttnn easier.

2025-01-06 14:26 UTC, ddilbazTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +        DefaultValuedAttr<I32Attr, "0">:$decimals
Hi Aleks! This is how ttnn round is defined by tt-metal: (third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/eltwise/unary/device/unary_composite_op.cpp) 

```
Tensor _round(const Tensor& input, int32_t decimals, const std::optional<MemoryConfig>& output_mem_config) {
    auto arch = input.device()->arch();
    TT_FATAL(arch == tt::ARCH::WORMHOLE_B0, "Op is only supported on Wormhole");
    Tensor floor_res = ttnn::floor(input, output_mem_config);
    if (decimals != 0) {  // TODO: For decimal value!=0
        Tensor power_10 = ttnn::power(ttnn::full_like(input, 10.0f), decimals, output_mem_config);
        Tensor rounded_non_half = ttnn::floor(
            ttnn::add(
                ttnn::multiply(input, power_10, std::nullopt, output_mem_config), 0.5, std::nullopt, output_mem_config),
            output_mem_config);
        rounded_non_half = ttnn::div(rounded_non_half, power_10);
        return rounded_non_half;
    } else {  // Bankers' Rounding
        Tensor rounded_non_half = ttnn::floor(
            ttnn::add(
                input,
                ttnn::where(
                    ttnn::logical_and(ttnn::ge(input, 0.4), ttnn::le(input, 0.5)),
                    0.4f,
                    0.5f,
                    output_mem_config.value()),
                std::nullopt,
                output_mem_config),
            output_mem_config.value());
        Tensor fractional_part = ttnn::subtract(input, floor_res, std::nullopt, output_mem_config);
        Tensor is_half = ttnn::eq(fractional_part, 0.5, std::nullopt, output_mem_config);
        Tensor rounded_half =
            ttnn::add(floor_res, is_odd(floor_res, output_mem_config), std::nullopt, output_mem_config);
        return ttnn::where(is_half, rounded_half, rounded_non_half, output_mem_config.value());
    }
}
```

However, we are trying to map two separate ops - round nearest even and round nearest away from zero - from stablehlo to ttnn. 

[round nearest away from zero](https://openxla.org/stablehlo/spec#round_nearest_afz) 
[round nearest even](https://openxla.org/stablehlo/spec#round_nearest_even)

Since there are two stablehlo round ops and since tt metal has the option to change mode based on decimals variable, I am keeping the stablehlo round ops, mapping them to ttir, and then using decimals variable when lowering to ttnn. 

For the difference in rounding between these two methods:
// %operand = [-2.5, 0.4, 0.5, 0.6, 2.5]
%result1 = "stablehlo.round_nearest_afz"(%operand) : (tensor<5xf64>) -> tensor<5xf64>
// %result1: [-3.0, 0.0, 1.0, 1.0, 3.0]
%result2 = "stablehlo.round_nearest_even"(%operand) : (tensor<5xf64>) -> tensor<5xf64>
// %result2: [-2.0, 0.0, 0.0, 1.0, 2.0]

2025-01-06 14:27 UTC, ddilbazTT commented on lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
> +    if (isa<stablehlo::RoundOp>(srcOp)) {
Could you clarify your suggestion please? Is it preferred to have two functions, each for one round op?

2025-01-06 14:29 UTC, ddilbazTT commented on lib/Dialect/TTIR/IR/TTIROps.cpp
> +  if (getDecimals() == 0) {
This comes from how the decimals value in tt metal round op is used. This is what we are trying to convert the stablehlo round ops to:

```
Tensor _round(const Tensor& input, int32_t decimals, const std::optional<MemoryConfig>& output_mem_config) {
    auto arch = input.device()->arch();
    TT_FATAL(arch == tt::ARCH::WORMHOLE_B0, "Op is only supported on Wormhole");
    Tensor floor_res = ttnn::floor(input, output_mem_config);
    if (decimals != 0) {  // TODO: For decimal value!=0
        Tensor power_10 = ttnn::power(ttnn::full_like(input, 10.0f), decimals, output_mem_config);
        Tensor rounded_non_half = ttnn::floor(
            ttnn::add(
                ttnn::multiply(input, power_10, std::nullopt, output_mem_config), 0.5, std::nullopt, output_mem_config),
            output_mem_config);
        rounded_non_half = ttnn::div(rounded_non_half, power_10);
        return rounded_non_half;
    } else {  // Bankers' Rounding
        Tensor rounded_non_half = ttnn::floor(
            ttnn::add(
                input,
                ttnn::where(
                    ttnn::logical_and(ttnn::ge(input, 0.4), ttnn::le(input, 0.5)),
                    0.4f,
                    0.5f,
                    output_mem_config.value()),
                std::nullopt,
                output_mem_config),
            output_mem_config.value());
        Tensor fractional_part = ttnn::subtract(input, floor_res, std::nullopt, output_mem_config);
        Tensor is_half = ttnn::eq(fractional_part, 0.5, std::nullopt, output_mem_config);
        Tensor rounded_half =
            ttnn::add(floor_res, is_odd(floor_res, output_mem_config), std::nullopt, output_mem_config);
        return ttnn::where(is_half, rounded_half, rounded_non_half, output_mem_config.value());
    }
}

```

2025-01-06 14:31 UTC, ddilbazTT commented on test/ttmlir/Conversion/StableHLOToTTIR/round_op.mlir
> +    // CHECK: %[[C:.*]] = tensor.empty[[C:.*]]
I'm sorry I don't follow - could you explain more? I was following similar tests under that directory. For example:
`test/ttmlir/Conversion/StableHLOToTTIR/floor_op.mlir`
```
// REQUIRES: stablehlo
// RUN: ttmlir-opt --stablehlo-to-ttir-pipeline %s | FileCheck %s
module @jit_eltwise_floor attributes {} {
  func.func public @test_floor(%arg0: tensor<32x32x3xf32>) -> tensor<32x32x3xf32> {
    %0 = stablehlo.floor %arg0 : tensor<32x32x3xf32>
    // CHECK: %[[C:.*]] = tensor.empty[[C:.*]]
    // CHECK: %[[C:.*]] = "ttir.floor"[[C:.*]]
    return %0 : tensor<32x32x3xf32>
  }
}
```

2025-01-06 14:32 UTC, ddilbazTT commented on lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
> +               DefaultOpConversionPattern<ttnn::RoundOp>,
Thank you for the catch!

2025-01-08 09:34 UTC, azecevicTT commented on include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
> +        Variadic<AnyRankedTensor>:$inputs,
We should either model it as close as possible to TTNN, in which case `TTNN_RoundOp` should be part of the (new) `TTNN_(Elementwise)UnaryCompositeOpWithInt(Parameter)` class, or model it as a separate op of `TTNN_Op` class. The way flatbuffer and runtime is implemented here it's pretty much 'generic with only one possible instance' to put it shortly, it doesn't make much sense and we should decide on either one (generic) or the other (concrete).
Also I'm not quite sure why are we making a distinction between composite and non-composite ops, it's an implementation detail on the Metal side, from the user (our) perspective I don't see any difference.

2025-01-08 10:02 UTC, azecevicTT commented on include/ttmlir/Dialect/TTIR/IR/TTIROps.td
> +        DefaultValuedAttr<I32Attr, "0">:$decimals
Yeah, I checked how round op is implemented in TTNN, as it says in the comment (else branch) it only ever uses `round_ne` (Banker's Rounding), I don't see `round_nafz` anywhere. I guess we can make a decomposition to simulate it with some multiplications, additions, and `round_ne`, but the question is should we, i.e. do we expect it to make any significant difference? The other big difference is that StableHLO doesn't model `decimals`. My guess is that it's because is not fundamental (it can be simulated with `mult`, `add`, `div` etc. similar to the composite code of `ttnn.round`), but StableHLO strive to be as general as possible, `decimals` is a standard parameter for every `round` op I have seen in existence, it exists in TTNN, so we should model it properly in our dialects as well.

I would propose to silently lower both `shlo.round_nafz` and `shlo.round_ne` to `ttir.round` that has a `decimals` parameter (both of these lower with a parameter equal to 0). Other option would be to introduce `ttir.round_nafz`, `ttir.round_ne` that don't have any additional parameters, with addition of `ttir.round` with `decimals` parameter and fold `ttir.round_ne` to `ttir.round(0)` directly, and decompose `ttir.round_nafz` to simulate it's behaviour. First option is much simpler, second has an advantage that it models the `ttir.round_nafz` correctly, I'm okay with either one, just find the first one more pragmatic as I don't expect the second one to make any difference (in any non-contrieved example).

2025-01-08 10:05 UTC, ddilbazTT commented on include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
> +        Variadic<AnyRankedTensor>:$inputs,
You can also see #1290 in the discussion that the decision between implementing TTNN_(Elementwise)UnaryCompositeOpWithInt(Parameter) or not does not make a difference. There are only few unary composite ops with int, and these ops don't seem to correspond to the rest of stablehlo ops we have yet to implement.

2025-01-08 10:16 UTC, azecevicTT commented on include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
> +        Variadic<AnyRankedTensor>:$inputs,
In that case we should treat it as a non-generic op, as it stands we pretend that it's the instance of generic but pretty much treat it as a non-generic, I just find it weird.

2025-01-08 10:28 UTC, azecevicTT commented on test/ttmlir/Conversion/StableHLOToTTIR/round_op.mlir
> +    // CHECK: %[[C:.*]] = tensor.empty[[C:.*]]
You have a tutorial here https://llvm.org/docs/CommandGuide/FileCheck.html. Yeah, some of the older tests doesn't make much sense, we should take care of them at some point, but we should at least try to avoid it in new tests.

2025-01-08 10:32 UTC, azecevicTT commented on lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
> +    if (isa<stablehlo::RoundOp>(srcOp)) {
In this case I find a separate function more suitable.  But depending on the final implementation template can be suitable here. I just think that template + dynamic_cast is a bad pattern.

2025-02-21 01:35 UTC, nsmithtt commented
This is an old PR, perhaps we can close?

2025-02-21 01:47 UTC, ddilbazTT commented
Yep - will re-open when done

2025-02-21 01:47 UTC, closed without merging