Renamed params in transpose op
tenstorrent/tt-mlir pull request #335
Opened 2024-08-09 14:48 UTC by vladimirjovanovicTT

Renamed params in transpose op from (..., dimension1, dimension2) to (..., dimension0, dimension1) to make integration with tt-forge streamlined and to make naming in-line with PyTorch (https://pytorch.org/docs/stable/generated/torch.transpose.html)

https://github.com/tenstorrent/tt-forge/pull/41

2024-08-09 14:49 UTC, nsmithtt approved these changes

2024-08-09 16:26 UTC, svuckovicTT approved these changes

2024-08-12 10:42 UTC, sdjordjevicTT requested changes
There are two commits in this change. I believe your intention is just to merge:
[Modified parameter names for transpose.](https://github.com/tenstorrent/tt-mlir/pull/335/commits/9294a7b9a82528b06f1da64dd5535368881fe402)

2024-08-19 13:44 UTC, sdjordjevicTT approved these changes

2024-08-19 13:46 UTC, merged