Fix bugs in stablehlo reduce op conversion
tenstorrent/tt-mlir pull request #899
Opened 2024-10-10 21:14 UTC by mmanzoorTT

2024-10-11 02:38 UTC, uazizTT reviewed
I think @mrakitaTT already made some fixes in this commit

https://github.com/tenstorrent/tt-mlir/commit/df424f226f9cbd652ef8788713bcde9c4f7dc7a6

2024-10-21 18:18 UTC, AleksKnezevic approved these changes

2024-10-21 18:19 UTC, LPanosTT approved these changes

2024-10-21 20:58 UTC, mrakitaTT requested changes
Discussed offline with Asif and Aleks, just to document the conclusions.

This is already tracked with #805, I've wrote there the current situation: https://github.com/tenstorrent/tt-mlir/issues/805#issuecomment-2388366556

I will escalate this metal issue in `TTNN Op Bugs/WAs` component and discuss if we can make the workaround since it doesn't seem likely that Metal team will fix this on their side.

If we decide to make a workaround, then I would rather close this PR and send the PR with the fixes that I've already made [here](https://github.com/tenstorrent/tt-mlir/commit/df424f226f9cbd652ef8788713bcde9c4f7dc7a6) and [here](https://github.com/tenstorrent/tt-mlir/commit/2d55a061e749a2b7e398e740c55320ff0de95a6e), because they cover this issue more generally. Fix that Asif made is working only for full reduce (across all dimensions).

Let's leave this PR open in case that we decide to wait on Metal team, because we can still support the specific case that Asif fixed without it being "workaround", though I would make a few changes to the code in that case.

2025-01-22 08:10 UTC, closed without merging